[tasks.clean-dist]
command = "trunk"
args = ["clean", "--cargo"]

[tasks.clean-release]
command = "trunk"
args = ["clean", "--cargo", "--dist", "release"]

[tasks.run-dev]
dependencies = ["clean-dist"]
command = "trunk"
args = ["serve", "--open"]

[tasks.build-release]
dependencies = ["clean-release"]
command = "trunk"
args = [
    "build",
    "--release",
    "--minify",
    "--dist",
    "release",
    "--public-url",
    "/lpnh.github.io/",
]

[tasks.run-release]
dependencies = ["build-release"]
command = "sh"
args = ["-c", "cp -r public/aux/* release/"]

[tasks.update-pages]
command = "git"
args = ["subtree", "push", "--prefix", "release", "origin", "gh-pages"]
